# Modelo de Regresi√≥n Para Desarrollo IBNR

In [1]:
import itertools
import pandas as pd
import re
import math
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [12]:
def columnas(valores,variable):
    y = [re.findall("\\d+", j)[0] for j in valores]
    y = [int(i) for i in y]
    todas = list(set(y))
    df = pd.DataFrame()
    df[f"y_{variable}"] = y
    for k in todas:
        #print(k)
        df[f"{variable}_{k}"] = ([1 if k == j else 0 for j in y])
    return df

def matrix_X(df_triangulo):
    k = len(df_triangulo.columns)
    alpha = [f'a_{i}' for i in range(1,k+1)]
    mu    = [f'u_{i}' for i in range(1,k+1)]
    lists = [alpha, mu]
    df    = pd.DataFrame(list(itertools.product(*lists)), columns=['a', 'u'])

    alpha    = columnas(valores  = df.a, variable = 'a')
    mu       = columnas(valores=df.u, variable = 'u')
    df_col= pd.concat([alpha, mu], axis=1)


    df_col['y_a'] = df_col['y_a'].astype(str) + df_col['y_u'].astype(str) 
    df_col['y_a'] = [int(i) for i in df_col['y_a']]
    df_col = df_col.drop(['y_u', 'u_1'], axis=1)
    df_col['a_1'] = 1
    df_col.rename(columns={'a_1': 'b0'}, inplace=True)
    df_col.rename(columns={'y_a': 'y_ii'}, inplace=True)
    #df_col = df_col.drop(['y_ii'], axis=1)
    return df_col


def matrix_y(df_triangulo):
    k = len(df_triangulo.columns)
    d0 = pd.DataFrame()
    for i in range(k):
        for j in range(k):
            d1 = pd.DataFrame({'y_ii': [int(f'{i+1}{j+1}')], 'Y': [math.log(df_triangulo.iloc[i, j])]})
            d0 = pd.concat([d0, d1], axis=0)
    return d0

def triangulo(df, grcode, entreno):
    
    if entreno:
        df_trinagulo = df[(df['GRCODE']== grcode ) & (df['DevelopmentYear']<=1997)].copy()
    else: 
        df_trinagulo = df[df['GRCODE']== grcode].copy()
        
    df_g         = df_trinagulo.groupby(["AccidentYear", "DevelopmentLag"]).agg({'IncurLoss_C': ['max']})
    df_g.columns = ['Pagos']
    df_g         = df_g.reset_index()
    pivot_data   = df_g.pivot(index='AccidentYear',columns='DevelopmentLag',values='Pagos').reset_index()
    pivot_data   = pivot_data.drop('AccidentYear', axis=1).cumsum(axis=1)
    
    return pivot_data



def entreno_prueba(df_trg_entreno, df_trg_prueba):

    Y = matrix_y(df_trg_entreno)
    X = matrix_X(df_trg_entreno)

    Y_X           = pd.merge(Y, X, on='y_ii', how='inner')
    data_entreno  = Y_X[Y_X['Y'].notna()]
    data_entreno  = data_entreno.drop(['y_ii'], axis=1)

    Y_prueba      = matrix_y(df_trg_prueba)                   
    x_prueba      = Y_X[Y_X['Y'].isna()].drop(['Y'], axis=1)

    data_prueba_  = pd.merge(Y_prueba, x_prueba, on='y_ii', how='inner')
    data_prueba_  = data_prueba_[data_prueba_['u_10']==1]
    data_prueba   = data_prueba_.drop(['y_ii'], axis=1)
    
    y_ii          = data_prueba_['y_ii']

    x_entreno = data_entreno.drop('Y', axis=1)  # Features
    y_entreno = data_entreno['Y']  # Target variable
    x_prueba  = data_prueba.drop('Y', axis=1)  # Features
    y_prueba  = data_prueba['Y']  # Target variable
    
    return x_entreno, y_entreno, x_prueba, y_prueba


def pagado_0(triangulo_prueba):
    n_ori, n_dev = triangulo_prueba.shape
    pagado_0 = []
    
    for j in range(n_ori):
        pagado_0.append(triangulo_prueba.iloc[j,n_ori-1-j])
    pagado_0.pop(0)
    return pagado_0



def escalar_0_1(y_entreno, y_prueba):
    
    min = np.min(pd.concat([y_entreno, y_prueba]))
    max = np.max(pd.concat([y_entreno, y_prueba]))
    y_entreno_scal = (y_entreno - min)/(max -  min)
    y_prueba_scal  = (y_prueba - min)/(max -  min)
    return y_entreno_scal, y_prueba_scal


## Trg entreno

In [18]:
df_data        = pd.read_csv('../comauto_pos.csv')
codig = 44598
df_trg_entreno = triangulo(df_data, grcode=266, entreno=True)
#df_trg_entreno
#set(df_data['GRCODE'])

## Trg Prueba

In [19]:
df_trg_prueba  = triangulo(df_data, grcode=codig, entreno=False)
df_trg_prueba

DevelopmentLag    1    2     3     4     5     6     7     8     9    10
0                74  135   175   207   243   279   315   351   387   423
1                65  130   244   287   327   367   407   447   487   527
2                70  161   201   241   281   322   363   404   445   486
3               108  170   253   336   418   500   583   666   749   832
4               102  250   642   997  1328  1659  1990  2321  2651  2983
5                98  161   251   316   381   447   513   579   646   712
6               182  483   622   756   907  1051  1195  1340  1484  1628
7               443  822  1110  1446  1790  2128  2458  2787  3116  3445
8                95  210   304   398   492   557   620   683   746   791
9               102  200   296   392   437   477   517   557   586   615

In [35]:
import math

def matrix_y(df_triangulo):
    k = len(df_triangulo)
    d0 = pd.DataFrame(columns=['y_ii', 'Y'])
    
    for i in range(k):
        for j in range(k):
            value = df_triangulo.iloc[i, j]
            if value > 0:  # Verificar si el valor es positivo
                d1 = pd.DataFrame({'y_ii': [int(f'{i+1}{j+1}')], 'Y': [math.log(value)]})
                d0 = pd.concat([d0, d1], axis=0)
    
    return d0

## Datos Entreno y Prueba

In [34]:
x_entreno, y_entreno, x_prueba, y_prueba = entreno_prueba(df_trg_entreno, df_trg_prueba)

### Modelo

In [31]:
model = LinearRegression()
model.fit(x_entreno, y_entreno)
y_pred = model.predict(x_prueba)
mse = mean_squared_error(y_prueba, y_pred)   # COnsiderar que se debe aplicar la exponencial a los rsultados
mse

Empty DataFrame
Columns: [b0, a_2, a_3, a_4, a_5, a_6, a_7, a_8, a_9, a_10, u_2, u_3, u_4, u_5, u_6, u_7, u_8, u_9, u_10]
Index: []

**Nota**: Deber√≠a comparar la columna de desarrollo del a√±o 10

In [ ]:

df_val = pd.DataFrame()

df_val['pago_0'] = pagado_0(df_trg_prueba)
df_val['pago_n'] = [round(math.exp(i)) for i in y_prueba]
df_val['pago_hat'] = [round(math.exp(i)) for i in y_pred]

df_val['pago_restante'] = df_val['pago_n'] - df_val['pago_0']
df_val['pago_ibnr'] = df_val['pago_hat'] - df_val['pago_0']
df_val['pago_diff'] = (df_val['pago_ibnr']/df_val['pago_restante'] - 1)*100

df_val

### Error

In [ ]:
print('Pago restante:', sum(df_val['pago_restante']))
print('IBNR Estimado:', sum(df_val['pago_ibnr']))
print('(IBNR/Pago)% :', (sum(df_val['pago_ibnr'])/sum(df_val['pago_restante'])-1)*100)

# LOOCV - Leave One Out Coss Validation

## Seleccionar compa√±ias  aptas

In [ ]:
GRCODE = list(set(df_data['GRCODE']))
GRCODE_aptos = []

for cod in GRCODE:
    trg  = triangulo(df_data, grcode=cod, entreno=False)
    apto = (trg.loc[0, 10] != 0) and (trg.loc[9,1] !=0)
    #print(cod)
    if apto:
        GRCODE_aptos.append(cod)
        
print('Los compa√±ias aptas son:',len(GRCODE_aptos))

In [ ]:
df_data_aptos  = df_data[df_data['GRCODE'].isin(GRCODE_aptos)]

cod = GRCODE_aptos[0]

df_trg_entreno = triangulo(df_data, grcode=669, entreno=True)
df_trg_prueba  = triangulo(df_data, grcode=669, entreno=False)
x_entreno, y_entreno, x_prueba, y_prueba = entreno_prueba(df_trg_entreno, df_trg_prueba)

In [ ]:
errores = []
for id_ in range(len(GRCODE_aptos)):
    cod = GRCODE_aptos[id_]
    print(id_)
    df_trg_entreno_t = triangulo(df_data, grcode=cod, entreno=True)
    df_trg_prueba_t  = triangulo(df_data, grcode=cod, entreno=False)
    x_entreno_t, y_entreno_t, x_prueba_t, y_prueba_t = entreno_prueba(df_trg_entreno_t, df_trg_prueba_t)
    y_entreno_scal_t, y_prueba_scal_t = escalar_0_1(y_entreno_t, y_prueba_t)       

    min_t = np.min(pd.concat([y_entreno, y_prueba]))
    max_t = np.max(pd.concat([y_entreno, y_prueba]))
    
    y_entr_concat    = pd.Series([0])
    x_entreno_concat = pd.DataFrame()


    for j in GRCODE_aptos:
    
        if j!=cod:
            df_trg_entreno = triangulo(df_data, grcode=j, entreno=True)
            df_trg_prueba  = triangulo(df_data, grcode=j, entreno=False)
            x_entreno, y_entreno, x_prueba, y_prueba = entreno_prueba(df_trg_entreno, df_trg_prueba)
            y_entreno_scal, y_prueba_scal = escalar_0_1(y_entreno, y_prueba)
            y_entr_concat = pd.concat([y_entr_concat, y_entreno_scal])
            x_entreno_concat = pd.concat([x_entreno_concat, x_entreno])
            #print(x_entreno.shape[0], len(y_entreno_scal))
    y_entr_concat = y_entr_concat.iloc[1:]


    model = LinearRegression()
    model.fit(x_entreno_concat, y_entr_concat)
    y_pred_scal = model.predict(x_prueba_t)
    y_pred_t  = [(max_t- min_t)*p + min_t   for p in y_pred_scal.tolist()]
    y_prueba_t  = [(max_t- min_t)*p + min_t   for p in y_prueba_scal_t.tolist()]

    df_val = pd.DataFrame()

    df_val['pago_0'] = pagado_0(df_trg_prueba)
    df_val['pago_n'] = [round(math.exp(i)) for i in y_prueba_t]
    df_val['pago_hat'] = [round(math.exp(i)) for i in y_pred_t]

    df_val['pago_restante'] = df_val['pago_n'] - df_val['pago_0']
    df_val['pago_ibnr'] = df_val['pago_hat'] - df_val['pago_0']
    df_val['pago_diff'] = (df_val['pago_ibnr']/df_val['pago_restante'] - 1)*100

    error = (sum(df_val['pago_ibnr'])/sum(df_val['pago_restante'])-1)*100

    errores.append(error)

In [ ]:
errores

## Error Absoluto

In [ ]:
errores_abs = [abs(i) for i in errores]
print(round(100*np.mean(errores_abs)),"%")

In [ ]:
## Modelo asignado para cada compa√±ia

In [ ]:
codig = 683
pago_ibnr     = []
GRCODE        = []
pago_restante = []
for codig in GRCODE_aptos:
    df_trg_entreno = triangulo(df_data, grcode=codig, entreno=True)
    df_trg_prueba  = triangulo(df_data, grcode=codig, entreno=False)
    x_entreno, y_entreno, x_prueba, y_prueba = entreno_prueba(df_trg_entreno, df_trg_prueba)
    model = RandomForestRegressor()#LinearRegression()
    model.fit(x_entreno, y_entreno)
    y_pred = model.predict(x_prueba)


    df_val = pd.DataFrame()

    df_val['pago_0'] = pagado_0(df_trg_prueba)
    df_val['pago_n'] = [round(math.exp(i)) for i in y_prueba]
    df_val['pago_hat'] = [round(math.exp(i)) for i in y_pred]

    df_val['pago_restante'] = df_val['pago_n'] - df_val['pago_0']
    df_val['pago_ibnr'] = df_val['pago_hat'] - df_val['pago_0']
    df_val['pago_diff'] = (df_val['pago_ibnr']/df_val['pago_restante'] - 1)*100
    #print(f'{codig}: (IBNR/Pago)% :', (sum(df_val['pago_ibnr'])/sum(df_val['pago_restante'])-1)*100,"%")
    pago_ibnr.append(sum(df_val['pago_ibnr']))
    GRCODE.append(codig)
    pago_restante.append(sum(df_val['pago_ibnr']))
    #print(sum(df_val['pago_restante']))

df_resultado_RL = pd.DataFrame()
df_resultado_RL['GRCODE'] = GRCODE
df_resultado_RL['IBNR_LM'] = pago_ibnr
#df_resultado_RL['pago_restante'] = pago_restante
df_resultado_RL

In [ ]:
resultado_CL = pd.read_excel("../Resultados/Chain_adder.xlsx") 
resultado_CL['IBNR'] = round(resultado_CL['IBNR'])
resultado_CL = resultado_CL.drop(['Estado','Diferencia_porc'], axis=1)
resultado_CL.rename(columns={'IBNR': 'IBNR_CL'}, inplace=True)
resultado_CL

In [ ]:
resultado = pd.merge(resultado_CL, df_resultado_RL, on='GRCODE', how='inner')
resultado['diff_CL'] = (resultado['IBNR_CL']/resultado['PAGADO']-1)*100
resultado['diff_LM'] = (resultado['IBNR_LM']/resultado['PAGADO']-1)*100
resultado